version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: /E0lZiubAjZhemO2k7Y0q7oJZivfJaFrFrcNHCCtNiGkTuJj50HWsgzIN9YZGQ6x
  PreReleaseSuffix: stable
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
build_script:
- cmd: .\build.ps1 -Target AppVeyor
artifacts:
- path: artifacts/packages/*.nupkg
- path: artifacts/coverage/*.xml
- path: artifacts/test-results/*.xml
- path: artifacts/resharper-reports/*.xml
- path: artifacts/resharper-reports/*.html
deploy:
- provider: NuGet
  server: https://www.myget.org/F/alhardy/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  skip_symbols: true